spring:
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:file:./camunda-h2-database'
    username: sa
    password: sa

camunda:
  bpm:
    admin-user:
      password: admin
      id: admin
      first-name: admin
      last-name: admin